// Sloty App Mock Data

import type { Master, Category, Booking, ServiceRequest, Chat } from './types';

export const categories: Category[] = [
  // Updated categories to match the new two‑row grid design
  { id: '1', name: 'Manicure',     nameRu: 'Маникюр',     icon: '💅', count: 234 },
  { id: '2', name: 'Pedicure',     nameRu: 'Педикюр',     icon: '🦶', count: 120 },
  { id: '3', name: 'Barber',       nameRu: 'Парикмахер',  icon: '💈', count: 189 },
  { id: '4', name: 'Makeup',       nameRu: 'Макияж',      icon: '💄', count: 143 },
  { id: '5', name: 'Massage',      nameRu: 'Массаж',      icon: '💆', count: 156 },
  { id: '6', name: 'Cosmetology',  nameRu: 'Косметология',icon: '✨', count: 143 },
  { id: '7', name: 'Brows',        nameRu: 'Брови',       icon: '👁️', count: 170 },
  { id: '8', name: 'Lashes',       nameRu: 'Ресницы',     icon: '💫', count: 198 },
  // Additional categories can remain for other parts of the app if needed
  { id: '9', name: 'Tattoo',       nameRu: 'Тату',        icon: '🎨', count: 87 },
  { id: '10', name: 'Photography', nameRu: 'Фото',        icon: '📷', count: 112 },
  { id: '11', name: 'Tutoring',    nameRu: 'Репетитор',   icon: '📚', count: 267 },
  { id: '12', name: 'Fitness',     nameRu: 'Фитнес',      icon: '🏋️', count: 134 },
  { id: '13', name: 'Psychology',  nameRu: 'Психолог',    icon: '🧠', count: 89 },
  { id: '14', name: 'Repair',      nameRu: 'Ремонт',      icon: '🔧', count: 178 },
  { id: '15', name: 'Pet Grooming',nameRu: 'Груминг',     icon: '🐕', count: 67 },
];

export const masters: Master[] = [
  {
    id: '1',
    name: 'Анна Петрова',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
    specialization: 'Маникюр, педикюр',
    rating: 4.9,
    reviewCount: 127,
    distance: 0.8,
    address: 'ул. Пушкина, 15',
    lat: 55.7558,
    lng: 37.6173,
    priceFrom: 1500,
    verified: true,
    nextAvailable: 'Сегодня, 15:00',
    tags: ['Гель-лак', 'Дизайн', 'Укрепление'],
    isFavorite: false,
    about: 'Профессиональный мастер маникюра с опытом более 7 лет. Использую только премиальные материалы.',
    services: [
      { id: 's1', name: 'Маникюр классический', price: 1500, duration: 60, description: 'Обработка кутикулы, придание формы' },
      { id: 's2', name: 'Маникюр с покрытием гель-лак', price: 2500, duration: 90, description: 'Маникюр + стойкое покрытие' },
      { id: 's3', name: 'Дизайн ногтей', price: 500, duration: 30, description: 'За 1 ноготь' },
      { id: 's4', name: 'Снятие покрытия', price: 500, duration: 20 },
    ],
    portfolio: [
      'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1607779097040-26e80aa78e66?w=400&h=400&fit=crop',
    ],
    reviews: [
      { id: 'r1', authorName: 'Мария', rating: 5, text: 'Отличный мастер! Очень аккуратная работа.', date: '2024-03-10' },
      { id: 'r2', authorName: 'Елена', rating: 5, text: 'Всегда хожу только к Анне. Рекомендую!', date: '2024-03-08' },
    ],
  },
  {
    id: '2',
    name: 'Дмитрий Волков',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
    specialization: 'Барбер',
    rating: 4.8,
    reviewCount: 89,
    distance: 1.2,
    address: 'ул. Ленина, 42',
    lat: 55.7612,
    lng: 37.6295,
    priceFrom: 1200,
    verified: true,
    nextAvailable: 'Сегодня, 17:30',
    tags: ['Fade', 'Борода', 'Стрижка'],
    isFavorite: true,
    about: 'Барбер с международным опытом. Специализация: классические и современные мужские стрижки.',
    services: [
      { id: 's1', name: 'Мужская стрижка', price: 1200, duration: 45 },
      { id: 's2', name: 'Стрижка + борода', price: 1800, duration: 60 },
      { id: 's3', name: 'Королевское бритье', price: 1500, duration: 40 },
      { id: 's4', name: 'Укладка', price: 500, duration: 15 },
    ],
    portfolio: [
      'https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=400&h=400&fit=crop',
    ],
    reviews: [
      { id: 'r1', authorName: 'Алексей', rating: 5, text: 'Лучший барбер в городе!', date: '2024-03-12' },
    ],
  },
  {
    id: '3',
    name: 'Ольга Сидорова',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
    specialization: 'Массаж',
    rating: 5.0,
    reviewCount: 203,
    distance: 2.1,
    address: 'пр. Мира, 78',
    lat: 55.7489,
    lng: 37.6102,
    priceFrom: 2500,
    verified: true,
    nextAvailable: 'Завтра, 10:00',
    tags: ['Лечебный', 'Релакс', 'Антицеллюлитный'],
    isFavorite: false,
    about: 'Сертифицированный массажист с медицинским образованием. 10+ лет опыта.',
    services: [
      { id: 's1', name: 'Общий массаж', price: 3500, duration: 60 },
      { id: 's2', name: 'Массаж спины', price: 2500, duration: 40 },
      { id: 's3', name: 'Антицеллюлитный массаж', price: 4000, duration: 60 },
      { id: 's4', name: 'Лимфодренажный массаж', price: 4500, duration: 90 },
    ],
    portfolio: [],
    reviews: [
      { id: 'r1', authorName: 'Наталья', rating: 5, text: 'Золотые руки! После массажа как заново родилась.', date: '2024-03-11' },
    ],
  },
  {
    id: '4',
    name: 'Екатерина Иванова',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop',
    specialization: 'Косметолог',
    rating: 4.7,
    reviewCount: 156,
    distance: 0.5,
    address: 'ул. Гагарина, 23',
    lat: 55.7534,
    lng: 37.6205,
    priceFrom: 3000,
    verified: true,
    nextAvailable: 'Сегодня, 19:00',
    tags: ['Чистка', 'Пилинг', 'Уходы'],
    isFavorite: false,
    about: 'Врач-косметолог. Индивидуальный подход к каждому клиенту.',
    services: [
      { id: 's1', name: 'Чистка лица', price: 3500, duration: 60 },
      { id: 's2', name: 'Пилинг', price: 4000, duration: 45 },
      { id: 's3', name: 'Увлажняющий уход', price: 3000, duration: 50 },
    ],
    portfolio: [
      'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400&h=400&fit=crop',
    ],
    reviews: [],
  },
  {
    id: '5',
    name: 'Михаил Козлов',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop',
    specialization: 'Репетитор математики',
    rating: 4.9,
    reviewCount: 78,
    distance: 3.2,
    address: 'онлайн / ул. Советская, 5',
    lat: 55.7401,
    lng: 37.6350,
    priceFrom: 2000,
    verified: true,
    nextAvailable: 'Завтра, 14:00',
    tags: ['ЕГЭ', 'ОГЭ', 'Олимпиады'],
    isFavorite: false,
    about: 'Преподаватель математики с 15-летним стажем. Подготовка к ЕГЭ на 90+ баллов.',
    services: [
      { id: 's1', name: 'Индивидуальное занятие', price: 2500, duration: 60 },
      { id: 's2', name: 'Подготовка к ЕГЭ', price: 3000, duration: 90 },
      { id: 's3', name: 'Онлайн-занятие', price: 2000, duration: 60 },
    ],
    portfolio: [],
    reviews: [],
  },
  {
    id: '6',
    name: 'Светлана Новикова',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop',
    specialization: 'Наращивание ресниц',
    rating: 4.8,
    reviewCount: 234,
    distance: 1.8,
    address: 'ул. Чехова, 12',
    lat: 55.7645,
    lng: 37.6089,
    priceFrom: 2000,
    verified: true,
    nextAvailable: 'Сегодня, 16:00',
    tags: ['Классика', '2D', '3D', 'Ламинирование'],
    isFavorite: true,
    about: 'Lash-мастер с международной сертификацией. Работаю только с премиальными материалами.',
    services: [
      { id: 's1', name: 'Классическое наращивание', price: 2500, duration: 120 },
      { id: 's2', name: 'Объемное 2D', price: 3500, duration: 150 },
      { id: 's3', name: 'Ламинирование ресниц', price: 2000, duration: 60 },
    ],
    portfolio: [
      'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?w=400&h=400&fit=crop',
    ],
    reviews: [],
  },
];

export const bookings: Booking[] = [
  {
    id: 'b1',
    masterId: '1',
    masterName: 'Анна Петрова',
    masterAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
    service: { id: 's2', name: 'Маникюр с покрытием гель-лак', price: 2500, duration: 90 },
    date: '2024-03-18',
    time: '15:00',
    status: 'upcoming',
    address: 'ул. Пушкина, 15',
  },
  {
    id: 'b2',
    masterId: '2',
    masterName: 'Дмитрий Волков',
    masterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
    service: { id: 's2', name: 'Стрижка + борода', price: 1800, duration: 60 },
    date: '2024-03-20',
    time: '11:00',
    status: 'upcoming',
    address: 'ул. Ленина, 42',
  },
  {
    id: 'b3',
    masterId: '3',
    masterName: 'Ольга Сидорова',
    masterAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
    service: { id: 's1', name: 'Общий массаж', price: 3500, duration: 60 },
    date: '2024-03-10',
    time: '14:00',
    status: 'completed',
    address: 'пр. Мира, 78',
  },
];

export const serviceRequests: ServiceRequest[] = [
  {
    id: 'req1',
    title: 'Нужен маникюр на свадьбу',
    description: 'Ищу мастера для свадебного маникюра. Хочу нежный дизайн с кристаллами. Важен выезд на дом.',
    category: 'Маникюр',
    budget: 5000,
    location: 'Центральный район',
    preferredDate: '2024-04-15',
    preferredTime: '10:00',
    authorName: 'Мария',
    createdAt: '2024-03-14',
    responsesCount: 5,
    status: 'open',
  },
  {
    id: 'req2',
    title: 'Репетитор по математике для 9 класса',
    description: 'Ищу репетитора для подготовки к ОГЭ. Занятия 2 раза в неделю, можно онлайн.',
    category: 'Репетитор',
    budget: 2500,
    location: 'Онлайн',
    authorName: 'Елена',
    createdAt: '2024-03-13',
    responsesCount: 8,
    status: 'open',
  },
  {
    id: 'req3',
    title: 'Массаж спины, есть проблемы с позвоночником',
    description: 'Нужен лечебный массаж от профессионала. Есть диагноз остеохондроз.',
    category: 'Массаж',
    budget: 4000,
    location: 'м. Парк культуры',
    authorName: 'Андрей',
    createdAt: '2024-03-12',
    responsesCount: 3,
    status: 'in_progress',
  },
];

export const chats: Chat[] = [
  {
    id: 'c1',
    participantId: '1',
    participantName: 'Анна Петрова',
    participantAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
    lastMessage: 'Жду вас в 15:00!',
    lastMessageTime: '10 мин назад',
    unreadCount: 1,
    relatedBookingId: 'b1',
  },
  {
    id: 'c2',
    participantId: '2',
    participantName: 'Дмитрий Волков',
    participantAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
    lastMessage: 'Отлично, записал вас на 11:00',
    lastMessageTime: 'вчера',
    unreadCount: 0,
    relatedBookingId: 'b2',
  },
];
